version: "3.8"

services:
  mymongo:
    image: mongo
    container_name: mymongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
